export const CHANGE_RECOMMEND_SCROLL_TOP = "detail/CHANGE_RECOMMEND_SCROLL_TOP"
export const CHANGE_CHECK_DETAIL = "detail/CHANGE_CHECK_DETAIL"

export const CHANGE_MARK_NAV = "detail/CHANGE_MARK_NAV"